---
- hosts: monitoring
  roles:
    - { role: prometheus-server,
        prometheus_home: "{{ opencb_root }}/prometheus",
        grafana_home: "{{ opencb_root }}/grafana",
        prometheus_server_node_exporters: "{{ groups['all'] }}" }
    - { role: elastic-server,
        elastic_server_home: "{{ opencb_root }}/elasticsearch" }
