---
- hosts: storage
  roles:
    - { role: mongo,
        mongo_suffix: "alignment",
        mongo_data: "{{ opencb_root }}/alignment_store",
        mongo_express_port: 8082 }
    - { role: mongo,
        mongo_suffix: "variant",
        mongo_data: "{{ opencb_root }}/variant_store",
        mongo_express_port: 8083 }
