---
language: python
python: "3.6"

# Use the new container infrastructure
sudo: false

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook master.yml --syntax-check
