---
- name: Ensure docker dir exists
  file:
    path: ./opencb-dockerfile
    state: directory
    mode: 0755

- name: Copy dockerfile
  template:
    src: dockerfile.j2
    dest: ./opencb-dockerfile/dockerfile

- name: Build opencb docker image
  docker_image:
    name: opencb-test
    path: ./opencb-dockerfile
    tag: v0.1

- name: Add tomcat container
  docker_container:
    name: opencb
    image: opencb-test:v0.1
    state: started
    published_ports:
    - 8080:8080
