---
- name: Ensure mongo data dir present
  file:
    path: "{{ minimal_storage_mongo_data }}"
    state: directory
    mode: 0750

- name: Add Mongo container
  docker_container:
    name: dev_mongo
    image: mongo:3.6.1-jessie
    state: started
    volumes:
    - "{{ minimal_storage_mongo_data }}:/data/db:rw"
    published_ports:
    - 27017:27017

- name: Ensure solr data dir present
  file:
    path: "{{ minimal_storage_solr_data }}"
    state: directory
    mode: 0750

- name: Ensure dockerfile dir exists
  file:
    path: ./opencb-solr-dockerfile
    state: directory
    mode: 0755

- name: Generate dockerfile
  template:
    src: dockerfile.j2
    dest: ./opencb-solr-dockerfile/dockerfile

- name: Build opencb-solr docker image
  docker_image:
    name: opencb-solr
    path: ./opencb-solr-dockerfile
    tag: v0.2

- name: Add Solr container
  docker_container:
    name: dev_solr
    image: opencb-solr:v0.2
    state: started
    volumes:
    - "{{ minimal_storage_solr_data }}:/opt/solr/mydata"
    published_ports:
    - 8983:8983

- name: check solr cores
  uri:
    url: "{{ minimal_storage_solr_get }}"
    method: GET
    return_content: yes
  register: cores

- name: Add solr core
  uri:
    url: "{{ minimal_storage_solr_create }}"
    method: GET
    status_code: 200
  when: "not ('my-new-core' in cores.content)"
