---
- name: Ensure docker dir exists
  file:
    path: ./opencb-dockerfile-filebeat
    state: directory
    mode: 0755

- name: Copy dockerfile
  template:
    src: dockerfile.j2
    dest: ./opencb-dockerfile-filebeat/dockerfile

- name: Build filebeat docker image
  docker_image:
    name: opencb-filebeat
    path: ./opencb-dockerfile-filebeat
    tag: v0.1.2

- name: Write out filebeat config
  template:
    src: filebeat.yml.j2
    dest: ./opencb-dockerfile-filebeat/filebeat.yml
    group: docker
    mode: 0750

- name: Add filebeat container
  docker_container:
    name: filebeat
    image: opencb-filebeat:v0.1.2
    state: started
    volumes:
      - ./opencb-dockerfile-filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:rw
