---
- name: Ensure docker dir exists
  file:
    path: "{{ filebeat_docker_home }}"
    state: directory
    mode: 0755

- name: Copy dockerfile
  template:
    src: dockerfile.j2
    dest: "{{ filebeat_docker_home }}/dockerfile"

- name: Build filebeat docker image
  docker_image:
    name: opencb-filebeat
    path: "{{ filebeat_docker_home }}"
    tag: v0.1.3

# TODO - need root and to chown the filebeat.yml file
- name: Write out filebeat config
  template:
    src: filebeat.yml.j2
    dest: "{{ filebeat_docker_home }}/filebeat.yml"
    mode: 0750 # TODO...

- name: Add filebeat container
  docker_container:
    name: filebeat
    image: opencb-filebeat:v0.1.3
    state: started
    volumes:
      - "{{ filebeat_docker_home }}/filebeat.yml:/usr/share/filebeat/filebeat.yml"
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:rw
