---
# $ grep vm.max_map_count /etc/sysctl.conf
# vm.max_map_count=262144

- name: Create elasticsearch data dir
  file:
    path: "{{ elastic_server_home }}/data"
    state: directory
    mode: 0777 # TODO...
    #group: 1000

- name: Add elasticsearch
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - 9200:9200
      - 9300:9300
    env:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      cluster.name: opencb-logs
      bootstrap.memory_lock: "true"
      ELASTIC_PASSWORD: changeme
      TAKE_FILE_OWNERSHIP: "true"
    ulimits:
        - "memlock:-1"  # TODO - does this do soft and hard?
    volumes:
        - "{{ elastic_server_home }}:/usr/share/elasticsearch/data:rw"

- name: Add kibana
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:6.1.1
    ports:
      - 5601:5601
    env:
      ELASTICSEARCH_URL: "http://{{ ansible_host }}:9200"
      ELASTIC_PASSWORD: changeme

- name: Add logstash
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:6.1.1
