---
# $ grep vm.max_map_count /etc/sysctl.conf
# vm.max_map_count=262144

- name: Create elasticsearch data dir
  file:
    path: "{{ elastic_server_home }}/data"
    state: directory
    mode: 0777 # TODO...
    #group: 1000

- name: Create elasticsearch docker network
  docker_network:
    name: elasticsearch

- name: Add elasticsearch
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    ports:
      - 9200:9200
      - 9300:9300
    env:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      cluster.name: opencb-logs
      bootstrap.memory_lock: "true"
      TAKE_FILE_OWNERSHIP: "true"
    ulimits:
        - "memlock:-1"  # TODO - does this do soft and hard?
    volumes:
        - "{{ elastic_server_home }}:/usr/share/elasticsearch/data:rw"
    networks:
      - name: elasticsearch
    purge_networks: yes

- name: Add kibana
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana-oss:6.1.2
    ports:
      - 5601:5601
    env:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    networks:
      - name: elasticsearch
      - name: bridge
    purge_networks: yes

# TODO...
#- name: Add logstash
#  docker_container:
#    name: logstash
#    image: docker.elastic.co/logstash/logstash-oss:6.1.2
