---
- name: Ensure mongo data dir present
  file:
    path: "{{ mongo_data }}"
    state: directory
    mode: 0750

- name: Create docker network
  docker_network:
    name: "{{ mongo_suffix }}"

- name: Add Mongo container
  docker_container:
    name: "mongo-{{ mongo_suffix }}"
    image: "mongo:{{ mongo_version }}-jessie"
    state: started
    volumes:
      - "{{ mongo_data }}:/data/db:rw"
    networks:
      - name: "{{ mongo_suffix }}"

- name: Add Mongo express container
  docker_container:
    name: "mongo-express-{{ mongo_suffix }}"
    image: mongo-express
    published_ports:
      - "{{ mongo_express_port }}:8081"
    env:
      ME_CONFIG_MONGODB_SERVER: "mongo-{{ mongo_suffix }}"
    networks:
      - name: "{{ mongo_suffix }}"
