---
- name: Ensure docker dir exists
  file:
    path: "{{ opencga_tomcat_docker }}"
    state: directory
    mode: 0755

- name: Generate dockerfile
  template:
    src: dockerfile.j2
    dest: "{{ opencga_tomcat_docker }}/dockerfile"

- name: Generate catalog config
  template:
    src: configuration.yml.j2
    dest: "{{ opencga_tomcat_docker }}/configuration.yml"

- name: Generate storage config
  template:
    src: storage-configuration.yml.j2
    dest: "{{ opencga_tomcat_docker }}/storage-configuration.yml"

- name: Build opencb docker image
  docker_image:
    name: opencb-test
    path: "{{ opencga_tomcat_docker }}"
    tag: v0.2

- name: Add tomcat container
  docker_container:
    name: opencga
    image: opencb-test:v0.2
    state: started
    published_ports:
      - 8080:8080
    volumes:
      - "{{ opencga_tomcat_docker }}/configuration.yml:/opt/opencga/conf/configuration.yml"
      - "{{ opencga_tomcat_docker }}/storage-configuration.yml:/opt/opencga/conf/storage-configuration.yml"
    networks:
      - name: "{{ opencga_tomcat_solr }}"
      - name: "{{ opencga_tomcat_mongo_catalog_suffix }}"
      - name: "{{ opencga_tomcat_mongo_alignment_suffix }}"
      - name: "{{ opencga_tomcat_mongo_variant_suffix }}"

# TODO: fails second time...
- name: install catalog
  command: 'docker exec opencga /bin/bash -c "/opt/opencga/bin/opencga-admin.sh catalog install --algorithm HS256 --secret-key asdf"'

- name: test login
  uri:
    url: http://localhost:8080/opencga-1.2.0/webservices/rest/v1/users/admin/login
    method: POST
    body_format: json
    body: '{ "password": "changeme" }'
    status_code: 200
  register: test_login

- debug:
    msg: "{{ test_login }}"
