---
- name: Ensure opencga docker dir exists
  file:
    path: "{{ opencga_tomcat_docker }}/opencga"
    state: directory
    mode: 0755

- name: Generate dockerfile
  template:
    src: dockerfile-daemon.j2
    dest: "{{ opencga_tomcat_docker }}/opencga/dockerfile"

- name: Build opencb-daemon docker image
  docker_image:
    name: opencb-daemon
    path: "{{ opencga_tomcat_docker }}/opencga"
    tag: v0.1

- name: Ensure docker dir exists
  file:
    path: "{{ opencga_tomcat_docker }}/tomcat"
    state: directory
    mode: 0755

- name: Generate dockerfile
  template:
    src: dockerfile.j2
    dest: "{{ opencga_tomcat_docker }}/tomcat/dockerfile"

- name: Build opencb-tomcat docker image
  docker_image:
    name: opencb-tomcat
    path: "{{ opencga_tomcat_docker }}/tomcat"
    tag: v0.1

- name: Generate catalog config
  template:
    src: configuration.yml.j2
    dest: "{{ opencga_tomcat_docker }}/configuration.yml"

- name: Generate storage config
  template:
    src: storage-configuration.yml.j2
    dest: "{{ opencga_tomcat_docker }}/storage-configuration.yml"

- name: Generate tutorial script
  template:
    src: tutorial.sh.j2
    dest: "{{ opencga_tomcat_docker }}/tutorial.sh"
    mode: 0755

- name: Add tomcat container
  docker_container:
    name: opencga
    image: opencb-tomcat:v0.1
    state: started
    published_ports:
      - 8080:8080
    volumes:
      - "{{ opencga_tomcat_docker }}/configuration.yml:/opt/opencga/conf/configuration.yml"
      - "{{ opencga_tomcat_docker }}/storage-configuration.yml:/opt/opencga/conf/storage-configuration.yml"
      - "{{ opencga_tomcat_docker }}/tutorial.sh:/opt/opencga/bin/tutorial.sh"
    networks:
      - name: "{{ opencga_tomcat_solr }}"
      - name: "{{ opencga_tomcat_mongo_catalog_suffix }}"
      - name: "{{ opencga_tomcat_mongo_alignment_suffix }}"
      - name: "{{ opencga_tomcat_mongo_variant_suffix }}"

- name: Add daemon container
  docker_container:
    name: opencga-daemon
    image: opencb-daemon:v0.1
    state: started
    volumes:
      - "{{ opencga_tomcat_docker }}/configuration.yml:/opt/opencga/conf/configuration.yml"
      - "{{ opencga_tomcat_docker }}/storage-configuration.yml:/opt/opencga/conf/storage-configuration.yml"
    networks:
      - name: "{{ opencga_tomcat_solr }}"
      - name: "{{ opencga_tomcat_mongo_catalog_suffix }}"
      - name: "{{ opencga_tomcat_mongo_alignment_suffix }}"
      - name: "{{ opencga_tomcat_mongo_variant_suffix }}"
    env:
      ADMIN_PASSWORD: "{{ opencga_tomcat_admin_password }}"

# TODO: these both fails second time...
- name: install catalog
  command: 'docker exec opencga /bin/bash -c "/opt/opencga/bin/opencga-admin.sh catalog install --algorithm HS256 --secret-key asdf"'

- name: Create test user
  command: 'docker exec opencga /bin/bash -c "/opt/opencga/bin/opencga-admin.sh users create -u test --email test@example.com --name Test --user-password test -p <<< {{ opencga_tomcat_admin_password }}"'

- name: test login
  uri:
    url: http://localhost:8080/opencga-1.2.0/webservices/rest/v1/users/admin/login
    method: POST
    body_format: json
    body: '{ "password": "{{ opencga_tomcat_admin_password }}" }'
    status_code: 200
  register: test_login

- debug:
    msg: "{{ test_login }}"
