---
version: '3'
volumes:
    opencga_sessions:
    mongo_catalog_data:
    mongo_store_data:
    solr_data:

networks:
    solr:
    mongo_catalog:
    mongo_store:
    client:

services:
    opencga_tomcat:
        build: ./opencga-tomcat
        hostname: opencga_tomcat
        ports:
          - 8080:8080
        volumes:
          - "opencga_sessions:/opt/opencga/sessions:z"
        networks:
          - "client"
          - "solr"
          - "mongo_catalog"
          - "mongo_store"
        depends_on:
          - solr
          - mongo_catalog
          - mongo_store
    opencga_daemon:
        build: ./opencga
        volumes:
          - "opencga_sessions:/opt/opencga/sessions:z"
        networks:
          - "solr"
          - "mongo_catalog"
          - "mongo_store"
        environment:
            - ADMIN_PASSWORD="secret_admin_password"
        depends_on:
          - opencga_tomcat
          - solr
          - mongo_catalog
          - mongo_store
    opencga_client:
        build: ./opencga
        command:
          - /opt/opencga/bin/tutorial.sh
        networks:
          - "client"
          - "mongo_catalog"
          - "mongo_store"
        environment:
            - ADMIN_PASSWORD="secret_admin_password"
        depends_on:
          - opencga_tomcat
    solr:
        build: ./opencga-solr
        hostname: solr
        volumes:
          - "solr_data:/opt/solr/mydata"
        networks:
          - solr
    mongo_catalog:
        hostname: mongo_catalog
        image: mongo:3.6.1-jessie
        volumes:
            - mongo_catalog_data:/data/db:rw
        networks:
          - "mongo_catalog"
    mongo_store:
        hostname: mongo_store
        image: mongo:3.6.1-jessie
        volumes:
            - mongo_store_data:/data/db:rw
        networks:
          - "mongo_store"
