---
global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'node'
    static_configs:
      - targets:
        - 'compose_prom-node-exporter_1:9100'

  - job_name: 'cAdvisor'
    static_configs:
      - targets:
        - 'compose_cadvisor_1:8080'
