# {{ ansible_managed }}

global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'sahara-test'

#rule_files:
#  - "alerts.rules"

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'node'
    static_configs:
      - targets:
{% for node in prometheus_server_node_exporters %}
        - '{{ node }}:9100'
{% endfor %}

  - job_name: 'cAdvisor'
    static_configs:
      - targets:
{% for node in prometheus_server_cadvisor %}
        - '{{ node }}:9080'
{% endfor %}
